ALTER TABLE "ProductVersion"
ALTER COLUMN "salePrice" DROP NOT NULL,
ALTER COLUMN "salePrice" TYPE DECIMAL(12,2),
ALTER COLUMN "costPrice" DROP NOT NULL,
ALTER COLUMN "costPrice" TYPE DECIMAL(12,2);

ALTER TABLE "BomComponent"
ALTER COLUMN "quantity" TYPE DECIMAL(12,4);

ALTER TABLE "EcoBomComponent"
ALTER COLUMN "quantity" TYPE DECIMAL(12,4);
